import { IMAGES } from "./constants";

export interface ProductVariant {
  sira_no: number;
  urun_kodu: string;
  olculer: string;
  moq: string;
  fiyat_carpanlari: string;
  hammadde_turu: string;
  kalinlik_seviyesi: string;
  baski_durumu: string;
  kargo_bant_tipi: string;
  kulp_tipi: string;
  koruk_detayi: string;
  geridonusum_orani: string;
  termin_suresi: string;
  zemin_rengi: string;
  irsaliye_cebi_detay: string;
  uyumlu_sektorler: string;
  kullanim_amaci: string;
  stok_durumu: "Var" | "Siparişle" | "Yok";
  baski_renk_yon: string;
  satis_sekli: string;
  priceText: string;
  birim_fiyati?: number;
  para_birimi?: "TL" | "USD";
  multipliers: Record<string, number>;
}

export interface TaxonomyProduct {
  id: string;
  name: string;
  desc: string;
  categoryKey: "kargo_eticaret" | "plastik_poset" | "kagit_karton" | "bez_tela" | "koruyucu_endustriyel";
  categoryLabel: string;
  malzeme: string;
  specLabel?: string;
  specValue: string;
  baski: string;
  unitText: string;
  priceText: string;
  birim_fiyati?: number;
  para_birimi?: "TL" | "USD";
  isPremiumPrice: boolean;
  stokDurumu: "Var" | "Siparişle" | "Yok";
  badges: string[];
  imgUrl: string;
  variants: ProductVariant[];
}

export const CATEGORIES = [
  { key: "kargo_eticaret", label: "E-TİCARET VE KARGO AMBALAJLARI", count: 6 },
  { key: "plastik_poset", label: "PLASTİK POŞETLER", count: 7 },
  { key: "kagit_karton", label: "KAĞIT VE KARTON ÇANTALAR", count: 3 },
  { key: "bez_tela", label: "BEZ VE TELA ÇANTALAR", count: 2 },
  { key: "koruyucu_endustriyel", label: "KORUYUCU VE ENDÜSTRİYEL AMBALAJ", count: 2 }
];

export const TAXONOMY_PRODUCTS: TaxonomyProduct[] = [
  {
    id: "tx-parent-1",
    name: "Baskılı (Logolu) Kargo Poşetleri",
    desc: "Marka logolu, yüksek mukavemetli co-ex yapısıyla yırtılmaz e-ticaret kargo poşeti.",
    categoryKey: "kargo_eticaret",
    categoryLabel: "E-TİCARET VE KARGO AMBALAJLARI",
    malzeme: "Co-Ex (LDPE)",
    specLabel: "Kalınlık",
    specValue: "65 Mikron",
    baski: "Baskılı",
    unitText: "Birim Fiyat (5.000 Adet Başlayan)",
    priceText: "₺1.45'den",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı", "Eko-Dostu", "Çok Satan"],
    imgUrl: IMAGES.kargoPlastik,
    variants: [
      {
        sira_no: 1,
        urun_kodu: "KRG-2030-01",
        olculer: "20 x 30 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "65 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0 (Ön Yüz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.87",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 2,
        urun_kodu: "KRG-2432-02",
        olculer: "24 x 32 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "65 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0 (Ön Yüz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.93",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 3,
        urun_kodu: "KRG-2838-03",
        olculer: "28 x 38 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "65 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0 (Ön Yüz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.29",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 4,
        urun_kodu: "KRG-3040-04",
        olculer: "30 x 40 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "65 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0 (Ön Yüz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.45",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 5,
        urun_kodu: "KRG-3545-05",
        olculer: "35 x 45 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "65 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0 (Ön Yüz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.90",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 6,
        urun_kodu: "KRG-4050-06",
        olculer: "40 x 50 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 1 (Ön-Arka)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.42",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 7,
        urun_kodu: "KRG-4555-07",
        olculer: "45 x 55 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 1 (Ön-Arka)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.99",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 8,
        urun_kodu: "KRG-5060-08",
        olculer: "50 x 60 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "75 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%30 Recycled",
        termin_suresi: "7 İş Günü",
        zemin_rengi: "Dışı Beyaz / İçi Siyah",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺3.19",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      }
    ]
  },
  {
    id: "tx-parent-2",
    name: "Cepli (Kendinden Fatura Cepli) Kargo Poşetleri",
    desc: "Fatura ve irsaliye yerleşimi için kendinden yapışkanlı şeffaf arka cepli poşet.",
    categoryKey: "kargo_eticaret",
    categoryLabel: "E-TİCARET VE KARGO AMBALAJLARI",
    malzeme: "Co-Ex (LDPE)",
    specLabel: "Kalınlık",
    specValue: "70 Mikron",
    baski: "Baskısız",
    unitText: "Birim Fiyat (5.000 Adet Başlayan)",
    priceText: "₺1.35'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız", "Eko-Dostu"],
    imgUrl: IMAGES.kargoCepli,
    variants: [
      {
        sira_no: 9,
        urun_kodu: "KRG-2030-09",
        olculer: "20 x 30 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.81",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 10,
        urun_kodu: "KRG-2432-10",
        olculer: "24 x 32 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.86",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 11,
        urun_kodu: "KRG-2838-11",
        olculer: "28 x 38 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.20",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 12,
        urun_kodu: "KRG-3040-12",
        olculer: "30 x 40 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.35",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 13,
        urun_kodu: "KRG-3545-13",
        olculer: "35 x 45 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.77",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 14,
        urun_kodu: "KRG-4050-14",
        olculer: "40 x 50 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.25",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 15,
        urun_kodu: "KRG-4555-15",
        olculer: "45 x 55 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "75 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.78",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 16,
        urun_kodu: "KRG-5060-16",
        olculer: "50 x 60 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "75 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Gri / Siyah",
        irsaliye_cebi_detay: "Var (Şeffaf Arka Cep)",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.97",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      }
    ]
  },
  {
    id: "tx-parent-3",
    name: "Standart (Baskısız) Kargo Poşetleri",
    desc: "Yüksek mukavemetli, siyah iç astarlı standart gri/opak kargo poşeti.",
    categoryKey: "kargo_eticaret",
    categoryLabel: "E-TİCARET VE KARGO AMBALAJLARI",
    malzeme: "Co-Ex (LDPE)",
    specLabel: "Kalınlık",
    specValue: "60 Mikron",
    baski: "Baskısız",
    unitText: "Birim Fiyat (5.000 Adet Başlayan)",
    priceText: "₺1.25'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız", "Eko-Dostu"],
    imgUrl: IMAGES.kargoPlastik,
    variants: [
      {
        sira_no: 17,
        urun_kodu: "KRG-2030-17",
        olculer: "20 x 30 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.75",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 18,
        urun_kodu: "KRG-2432-18",
        olculer: "24 x 32 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.80",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 19,
        urun_kodu: "KRG-2838-19",
        olculer: "28 x 38 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.11",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 20,
        urun_kodu: "KRG-3040-20",
        olculer: "30 x 40 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.25",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 21,
        urun_kodu: "KRG-3545-21",
        olculer: "35 x 45 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE) ",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.64",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 22,
        urun_kodu: "KRG-4050-22",
        olculer: "40 x 50 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.08",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 23,
        urun_kodu: "KRG-4555-23",
        olculer: "45 x 55 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.58",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 24,
        urun_kodu: "KRG-5060-24",
        olculer: "50 x 60 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Co-Ex (LDPE)",
        kalinlik_seviyesi: "75 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%50 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Siyah / Gri",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.75",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      }
    ]
  },
  {
    id: "tx-parent-4",
    name: "Kağıt Kargo Poşetleri",
    desc: "Sürdürülebilir, geri dönüştürülebilir ve dayanıklı kraft kağıttan üretilmiş kargo ambalajı.",
    categoryKey: "kargo_eticaret",
    categoryLabel: "E-TİCARET VE KARGO AMBALAJLARI",
    malzeme: "Kahverengi Kraft",
    specLabel: "Gramaj",
    specValue: "110 Gr/m²",
    baski: "Baskısız",
    unitText: "Birim Fiyat (5.000 Adet Başlayan)",
    priceText: "₺2.80'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız", "Eko-Dostu", "Çok Satan"],
    imgUrl: IMAGES.kargoKagit,
    variants: [
      {
        sira_no: 25,
        urun_kodu: "KRG-2030-25",
        olculer: "20 x 30 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Kahverengi Kraft",
        kalinlik_seviyesi: "110 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Alt Körük (4 cm)",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Doğal Kraft (Kahve)",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.85",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 26,
        urun_kodu: "KRG-2432-26",
        olculer: "24 x 32 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Kahverengi Kraft",
        kalinlik_seviyesi: "110 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Alt Körük (5 cm)",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Doğal Kraft (Kahve)",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.36",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 27,
        urun_kodu: "KRG-3040-27",
        olculer: "30 x 40 + 5 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Kahverengi Kraft",
        kalinlik_seviyesi: "120 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Alt Körük (6 cm)",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Doğal Kraft (Kahve)",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺3.69",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      }
    ]
  },
  {
    id: "tx-parent-5",
    name: "Fatura Cebi ve İrsaliye Zarfları",
    desc: "Kolilerin ve paketlerin üzerine yapıştırılan şeffaf, yapışkanlı polietilen cep.",
    categoryKey: "kargo_eticaret",
    categoryLabel: "E-TİCARET VE KARGO AMBALAJLARI",
    malzeme: "LDPE (Şeffaf)",
    specLabel: "Kalınlık",
    specValue: "40 Mikron",
    baski: "Baskısız",
    unitText: "Birim Fiyat (5.000 Adet Başlayan)",
    priceText: "₺0.45'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız", "Eko-Dostu"],
    imgUrl: IMAGES.faturaCebi,
    variants: [
      {
        sira_no: 28,
        urun_kodu: "KRG-1424-28",
        olculer: "14 x 24 (C5 Boyut)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "40 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kendinden Yapışkanlı",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Süper Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Evrak Cebi",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.27",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 29,
        urun_kodu: "KRG-1824-29",
        olculer: "18 x 24 (Standart)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "40 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kendinden Yapışkanlı",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Süper Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Evrak Cebi",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.27",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 30,
        urun_kodu: "KRG-2432-30",
        olculer: "24 x 32 (A4 Boyut)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "45 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kendinden Yapışkanlı",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Recycled",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Süper Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Evrak Cebi",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.29",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      }
    ]
  },
  {
    id: "tx-parent-6",
    name: "Balonlu Kargo Zarfları",
    desc: "Dış yüzeyi parlak, iç yüzeyindeki hava kabarcıklı korumasıyla hassas gönderi zarfı.",
    categoryKey: "kargo_eticaret",
    categoryLabel: "E-TİCARET VE KARGO AMBALAJLARI",
    malzeme: "Kraft + Balon PE",
    specLabel: "Kalınlık",
    specValue: "110 Mikron",
    baski: "Baskısız",
    unitText: "Birim Fiyat (5.000 Adet Başlayan)",
    priceText: "₺2.75'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız"],
    imgUrl: IMAGES.balonluZarf,
    variants: [
      {
        sira_no: 31,
        urun_kodu: "KRG-1525-31",
        olculer: "15 x 25 + 4 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Kraft + Balon PE",
        kalinlik_seviyesi: "110 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Altın Sarısı / Beyaz",
        irsaliye_cebi_detay: "İç Koruyucu Patpatlı",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.65",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 32,
        urun_kodu: "KRG-2025-32",
        olculer: "20 x 25 + 4 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Kraft + Balon PE",
        kalinlik_seviyesi: "110 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Altın Sarısı / Beyaz",
        irsaliye_cebi_detay: "İç Koruyucu Patpatlı",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.65",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 33,
        urun_kodu: "KRG-2535-33",
        olculer: "25 x 35 + 4 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Kraft + Balon PE",
        kalinlik_seviyesi: "110 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Altın Sarısı / Beyaz",
        irsaliye_cebi_detay: "İç Koruyucu Patpatlı",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.01",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      },
      {
        sira_no: 34,
        urun_kodu: "KRG-3040-34",
        olculer: "30 x 40 + 4 (Kapak)",
        moq: "5.000 Adet",
        fiyat_carpanlari: "5k:1.00 / 10k:0.92 / 25k:0.85",
        hammadde_turu: "Kraft + Balon PE",
        kalinlik_seviyesi: "120 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Tek Bant (Kalıcı)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "2 İş Günü",
        zemin_rengi: "Altın Sarısı / Beyaz",
        irsaliye_cebi_detay: "İç Koruyucu Patpatlı",
        uyumlu_sektorler: "E-Ticaret, Tekstil, Lojistik, Kozmetik",
        kullanim_amaci: "Güvenli kargo ve e-ticaret lojistik sevkiyatı",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.75",
        multipliers: {"5000": 1.0, "10000": 0.92, "25000": 0.85}
      }
    ]
  },
  {
    id: "tx-parent-7",
    name: "Mağaza Poşeti - El Geçme",
    desc: "Perakende, giyim ve butikleriniz için pürüzsüz parlak veya mat bitişli takviyeli el geçme poşet.",
    categoryKey: "plastik_poset",
    categoryLabel: "PLASTİK POŞETLER",
    malzeme: "LDPE (Parlak)",
    specLabel: "Kalınlık",
    specValue: "60 Mikron",
    baski: "Baskılı (Opsiyonel)",
    unitText: "Birim Fiyat (200 Kg Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı (Opsiyonel)", "Eko-Dostu", "Çok Satan"],
    imgUrl: IMAGES.magazaElGecme,
    variants: [
      {
        sira_no: 35,
        urun_kodu: "MGZ-2030-35",
        olculer: "20 x 30 + 5 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Parlak)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskılı (Opsiyonel)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%20 Recycled",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Beyaz / Renkli",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 1 (Ön-Arka)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 36,
        urun_kodu: "MGZ-2638-36",
        olculer: "26 x 38 + 6 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Parlak)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskılı (Opsiyonel)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%20 Recycled",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Beyaz / Renkli",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 1 (Ön-Arka)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 37,
        urun_kodu: "MGZ-3345-37",
        olculer: "33 x 45 + 6 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Parlak)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskılı (Opsiyonel)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%20 Recycled",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Beyaz / Renkli",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 1 (Ön-Arka)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 38,
        urun_kodu: "MGZ-4050-38",
        olculer: "40 x 50 + 8 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Parlak)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskılı (Opsiyonel)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%20 Recycled",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Beyaz / Renkli",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 39,
        urun_kodu: "MGZ-5060-39",
        olculer: "50 x 60 + 8 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Parlak)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskılı (Opsiyonel)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%20 Recycled",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Beyaz / Renkli",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      }
    ]
  },
  {
    id: "tx-parent-8",
    name: "Mağaza Poşeti - Takviyeli",
    desc: "Ağır tekstil ürünleri ve ayakkabı kutuları için el geçme yerinden ekstra kaynak takviyeli.",
    categoryKey: "plastik_poset",
    categoryLabel: "PLASTİK POŞETLER",
    malzeme: "LDPE (Alçak Yoğ.)",
    specLabel: "Kalınlık",
    specValue: "70 Mikron",
    baski: "Baskılı",
    unitText: "Birim Fiyat (200 Kg Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı"],
    imgUrl: IMAGES.magazaElGecme,
    variants: [
      {
        sira_no: 40,
        urun_kodu: "MGZ-2638-40",
        olculer: "26 x 38 + 6 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Alçak Yoğ.)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Takviyeli El Geçme",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Özel Pantone",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 41,
        urun_kodu: "MGZ-3345-41",
        olculer: "33 x 45 + 6 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Alçak Yoğ.)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Takviyeli El Geçme",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Özel Pantone",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 42,
        urun_kodu: "MGZ-4050-42",
        olculer: "40 x 50 + 8 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Alçak Yoğ.)",
        kalinlik_seviyesi: "70 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Takviyeli El Geçme",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Özel Pantone",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 43,
        urun_kodu: "MGZ-5060-43",
        olculer: "50 x 60 + 10 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Alçak Yoğ.)",
        kalinlik_seviyesi: "80 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Takviyeli El Geçme",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Özel Pantone",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "3 + 3 (Çok Renk)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      }
    ]
  },
  {
    id: "tx-parent-9",
    name: "Mağaza Poşeti - Yumuşak Saplı",
    desc: "Lüks mağaza deneyimi için gövdeden harici olarak kaynaklanmış şerit kulplu taşıma poşeti.",
    categoryKey: "plastik_poset",
    categoryLabel: "PLASTİK POŞETLER",
    malzeme: "LDPE (Yumuşak)",
    specLabel: "Kalınlık",
    specValue: "80 Mikron",
    baski: "Baskılı",
    unitText: "Birim Fiyat (200 Kg Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı"],
    imgUrl: IMAGES.magazaSapli,
    variants: [
      {
        sira_no: 44,
        urun_kodu: "MGZ-2638-44",
        olculer: "26 x 38 + 8 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Yumuşak)",
        kalinlik_seviyesi: "80 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yumuşak Sap (Soft)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Parlak Beyaz",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 45,
        urun_kodu: "MGZ-3345-45",
        olculer: "33 x 45 + 8 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Yumuşak)",
        kalinlik_seviyesi: "80 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yumuşak Sap (Soft)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Parlak Beyaz",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 46,
        urun_kodu: "MGZ-4050-46",
        olculer: "40 x 50 + 10 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Yumuşak)",
        kalinlik_seviyesi: "80 Mikron",
        baski_durumu: "Baskılı nudge",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yumuşak Sap (Soft)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Parlak Beyaz",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2 (Çift Yön)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 47,
        urun_kodu: "MGZ-5060-47",
        olculer: "50 x 60 + 10 (Alt Körük)",
        moq: "200 Kg",
        fiyat_carpanlari: "200kg:1.00 / 500kg:0.90 / 1ton:0.82",
        hammadde_turu: "LDPE (Yumuşak)",
        kalinlik_seviyesi: "90 Mikron",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yumuşak Sap (Soft)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%10 Saf Hammadde",
        termin_suresi: "12 İş Günü",
        zemin_rengi: "Parlak Beyaz",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Tekstil Mağazaları, Perakende, Butikler",
        kullanim_amaci: "Marka logolu perakende alışveriş taşımacılığı",
        stok_durumu: "Siparişle",
        baski_renk_yon: "3 + 3 (Çok Renk)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      }
    ]
  },
  {
    id: "tx-parent-10",
    name: "Market Poşetleri - Atlet",
    desc: "Market, eczane ve manavlar için yüksek taşıma mukavemetine sahip ekonomik hışır poşet.",
    categoryKey: "plastik_poset",
    categoryLabel: "PLASTİK POŞETLER",
    malzeme: "HDPE (Hışır)",
    specLabel: "Kalınlık",
    specValue: "16 Mikron",
    baski: "Standart Baskılı",
    unitText: "Birim Fiyat (300 Kg Başlayan)",
    priceText: "₺0.25'den",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Standart Baskılı", "Çok Satan"],
    imgUrl: IMAGES.marketAtlet,
    variants: [
      {
        sira_no: 48,
        urun_kodu: "MKT-2035-48",
        olculer: "20 x 35 + 10 (Yan Körük)",
        moq: "300 Kg",
        fiyat_carpanlari: "300kg:1.00 / 1ton:0.88 / 3ton:0.80",
        hammadde_turu: "HDPE (Hışır)",
        kalinlik_seviyesi: "16 Mikron",
        baski_durumu: "Standart Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Atlet Tipi (Saplı)",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Biyobozunur (d2w)",
        termin_suresi: "10 İş Günü",
        zemin_rengi: "Beyaz / Şeffaf",
        irsaliye_cebi_detay: "Hava Tahliye Delikli",
        uyumlu_sektorler: "Süpermarketler, Manavlar, Kasaplar, Şarküteriler",
        kullanim_amaci: "Hızlı Tüketim ve market ürünleri taşıması",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0 (Ön Yüz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.16",
        multipliers: {}
      },
      {
        sira_no: 49,
        urun_kodu: "MKT-2545-49",
        olculer: "25 x 45 + 12 (Yan Körük)",
        moq: "300 Kg",
        fiyat_carpanlari: "300kg:1.00 / 1ton:0.88 / 3ton:0.80",
        hammadde_turu: "HDPE (Hışır)",
        kalinlik_seviyesi: "16 Mikron",
        baski_durumu: "Standart Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Atlet Tipi (Saplı)",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Biyobozunur (d2w)",
        termin_suresi: "10 İş Günü",
        zemin_rengi: "Beyaz / Şeffaf",
        irsaliye_cebi_detay: "Hava Tahliye Delikli",
        uyumlu_sektorler: "Süpermarketler, Manavlar, Kasaplar, Şarküteriler",
        kullanim_amaci: "Hızlı Tüketim ve market ürünleri taşıması",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0 (Ön Yüz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.25",
        multipliers: {}
      },
      {
        sira_no: 50,
        urun_kodu: "MKT-2750-50",
        olculer: "27 x 50 + 12 (Yan Körük)",
        moq: "300 Kg",
        fiyat_carpanlari: "300kg:1.00 / 1ton:0.88 / 3ton:0.80",
        hammadde_turu: "HDPE (Hışır)",
        kalinlik_seviyesi: "16 Mikron",
        baski_durumu: "Standart Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Atlet Tipi (Saplı)",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Biyobozunur (d2w)",
        termin_suresi: "10 İş Günü",
        zemin_rengi: "Beyaz / Şeffaf",
        irsaliye_cebi_detay: "Hava Tahliye Delikli",
        uyumlu_sektorler: "Süpermarketler, Manavlar, Kasaplar, Şarküteriler",
        kullanim_amaci: "Hızlı Tüketim ve market ürünleri taşıması",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0 (Ön Yüz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.30",
        multipliers: {}
      },
      {
        sira_no: 51,
        urun_kodu: "MKT-3060-51",
        olculer: "30 x 60 + 14 (Yan Körük)",
        moq: "300 Kg",
        fiyat_carpanlari: "300kg:1.00 / 1ton:0.88 / 3ton:0.80",
        hammadde_turu: "HDPE (Hışır) ",
        kalinlik_seviyesi: "16 Mikron",
        baski_durumu: "Standart Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Atlet Tipi (Saplı)",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Biyobozunur (d2w)",
        termin_suresi: "10 İş Günü",
        zemin_rengi: "Beyaz / Şeffaf",
        irsaliye_cebi_detay: "Hava Tahliye Delikli",
        uyumlu_sektorler: "Süpermarketler, Manavlar, Kasaplar, Şarküteriler",
        kullanim_amaci: "Hızlı Tüketim ve market ürünleri taşıması",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0 (Ön Yüz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.40",
        multipliers: {}
      },
      {
        sira_no: 52,
        urun_kodu: "MKT-3570-52",
        olculer: "35 x 70 + 16 (Yan Körük)",
        moq: "300 Kg",
        fiyat_carpanlari: "300kg:1.00 / 1ton:0.88 / 3ton:0.80",
        hammadde_turu: "HDPE (Hışır)",
        kalinlik_seviyesi: "18 Mikron",
        baski_durumu: "Standart Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Atlet Tipi (Saplı)",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Biyobozunur (d2w)",
        termin_suresi: "10 İş Günü",
        zemin_rengi: "Beyaz / Şeffaf",
        irsaliye_cebi_detay: "Hava Tahliye Delikli",
        uyumlu_sektorler: "Süpermarketler, Manavlar, Kasaplar, Şarküteriler",
        kullanim_amaci: "Hızlı Tüketim ve market ürünleri taşıması",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0 (Ön Yüz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.54",
        multipliers: {}
      }
    ]
  },
  {
    id: "tx-parent-11",
    name: "Kilitli & Fermuarlı Poşetler",
    desc: "Gıdanın ve medikal ürünlerin tazeliğini ve hijyenini koruyan zipli kilit torba.",
    categoryKey: "plastik_poset",
    categoryLabel: "PLASTİK POŞETLER",
    malzeme: "LDPE (Şeffaf)",
    specLabel: "Kalınlık",
    specValue: "50 Mikron",
    baski: "Baskısız",
    unitText: "Birim Fiyat (1.000 Adet Başlayan)",
    priceText: "₺4.20'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız"],
    imgUrl: IMAGES.doypackKilitli,
    variants: [
      {
        sira_no: 53,
        urun_kodu: "KLT-811-53",
        olculer: "8 x 11",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "50 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Kilitli (Zip-lock)",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Kilitli Kırmızı Hat",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.52",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 54,
        urun_kodu: "KLT-1114-54",
        olculer: "11 x 14",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "50 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Kilitli (Zip-lock)",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Kilitli Kırmızı Hat",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺4.20",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 55,
        urun_kodu: "KLT-1318-55",
        olculer: "13 x 18",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "50 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Kilitli (Zip-lock)",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Kilitli Kırmızı Hat",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺6.38",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 56,
        urun_kodu: "KLT-1622-56",
        olculer: "16 x 22",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "50 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Kilitli (Zip-lock)",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Kilitli Kırmızı Hat",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺9.24",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 57,
        urun_kodu: "KLT-2025-57",
        olculer: "20 x 25",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "55 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Kilitli (Zip-lock)",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Kilitli Kırmızı Hat",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺9.24",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 58,
        urun_kodu: "KLT-2535-58",
        olculer: "25 x 35",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "LDPE (Şeffaf)",
        kalinlik_seviyesi: "60 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Kilitli (Zip-lock)",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Şeffaf",
        irsaliye_cebi_detay: "Şeffaf Kilitli Kırmızı Hat",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺9.24",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      }
    ]
  },
  {
    id: "tx-parent-12",
    name: "Jelatin & OPP Poşetler",
    desc: "Tekstil paketlemesinde kullanılan, kendinden yapışkanlı veya düz ultra parlak koruyucu naylon.",
    categoryKey: "plastik_poset",
    categoryLabel: "PLASTİK POŞETLER",
    malzeme: "OPP / PP",
    specLabel: "Kalınlık",
    specValue: "30 Mikron",
    baski: "Baskısız",
    unitText: "Birim Fiyat (1.000 Adet Başlayan)",
    priceText: "₺0.60'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız"],
    imgUrl: IMAGES.oppJelatin,
    variants: [
      {
        sira_no: 59,
        urun_kodu: "JLT-1015-59",
        olculer: "10 x 15",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "OPP / PP",
        kalinlik_seviyesi: "30 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kapak Bandı (Yapışkan)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Süper Parlak Şeffaf",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.36",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 60,
        urun_kodu: "JLT-1520-60",
        olculer: "15 x 20",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "OPP / PP",
        kalinlik_seviyesi: "30 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kapak Bandı (Yapışkan)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Süper Parlak Şeffaf",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.60",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 61,
        urun_kodu: "JLT-2030-61",
        olculer: "20 x 30",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "OPP / PP",
        kalinlik_seviyesi: "30 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kapak Bandı (Yapışkan)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Süper Parlak Şeffaf",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.20",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 62,
        urun_kodu: "JLT-2535-62",
        olculer: "25 x 35",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "OPP / PP",
        kalinlik_seviyesi: "35 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kapak Bandı (Yapışkan)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Süper Parlak Şeffaf",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.32",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      },
      {
        sira_no: 63,
        urun_kodu: "JLT-3040-63",
        olculer: "30 x 40",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 10k:0.88 / 50k:0.80",
        hammadde_turu: "OPP / PP",
        kalinlik_seviyesi: "35 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Kapak Bandı (Yapışkan)",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "3 İş Günü",
        zemin_rengi: "Süper Parlak Şeffaf",
        irsaliye_cebi_detay: "Yok",
        uyumlu_sektorler: "Gıda, Tekstil Aksesuar, Bijuteri, Kırtasiye",
        kullanim_amaci: "Küçük hacimli ürünlerin hijyenik paketlenmesi",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺1.32",
        multipliers: {"1000": 1.0, "10000": 0.88, "50000": 0.8}
      }
    ]
  },
  {
    id: "tx-parent-13",
    name: "Biyobozunur Poşetler",
    desc: "Mısır nişastası bazlı, çevreye zarar vermeden doğada %100 kompost olabilen ekolojik poşet.",
    categoryKey: "plastik_poset",
    categoryLabel: "PLASTİK POŞETLER",
    malzeme: "PLA / Nişasta",
    specLabel: "Kalınlık",
    specValue: "45 Mikron",
    baski: "Baskılı (Çevreci)",
    unitText: "Birim Fiyat (250 Kg Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı (Çevreci)", "Eko-Dostu", "Çok Satan"],
    imgUrl: IMAGES.biyobozunur,
    variants: [
      {
        sira_no: 64,
        urun_kodu: "BIO-2030-64",
        olculer: "20 x 30 + 5 (Alt Körük)",
        moq: "250 Kg",
        fiyat_carpanlari: "250kg:1.00 / 500kg:0.92 / 1ton:0.85",
        hammadde_turu: "PLA / Nişasta",
        kalinlik_seviyesi: "45 Mikron",
        baski_durumu: "Baskılı (Çevreci)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%100 Kompostlanabilir",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Mat Yeşil / Doğal",
        irsaliye_cebi_detay: "Doğada Çözünür Baskılı",
        uyumlu_sektorler: "Çevreci Markalar, Organik Gıda, Butikler",
        kullanim_amaci: "Doğa dostu, kompostlanabilir taşımacılık çözümü",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 1",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 65,
        urun_kodu: "BIO-2638-65",
        olculer: "26 x 38 + 6 (Alt Körük)",
        moq: "250 Kg",
        fiyat_carpanlari: "250kg:1.00 / 500kg:0.92 / 1ton:0.85",
        hammadde_turu: "PLA / Nişasta",
        kalinlik_seviyesi: "45 Mikron",
        baski_durumu: "Baskılı (Çevreci)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%100 Kompostlanabilir",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Mat Yeşil / Doğal",
        irsaliye_cebi_detay: "Doğada Çözünür Baskılı",
        uyumlu_sektorler: "Çevreci Markalar, Organik Gıda, Butikler",
        kullanim_amaci: "Doğa dostu, kompostlanabilir taşımacılık çözümü",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 1",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 66,
        urun_kodu: "BIO-3345-66",
        olculer: "33 x 45 + 6 (Alt Körük)",
        moq: "250 Kg",
        fiyat_carpanlari: "250kg:1.00 / 500kg:0.92 / 1ton:0.85",
        hammadde_turu: "PLA / Nişasta",
        kalinlik_seviyesi: "45 Mikron",
        baski_durumu: "Baskılı (Çevreci)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%100 Kompostlanabilir",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Mat Yeşil / Doğal",
        irsaliye_cebi_detay: "Doğada Çözünür Baskılı",
        uyumlu_sektorler: "Çevreci Markalar, Organik Gıda, Butikler",
        kullanim_amaci: "Doğa dostu, kompostlanabilir taşımacılık çözümü",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 1",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 67,
        urun_kodu: "BIO-4050-67",
        olculer: "40 x 50 + 8 (Alt Körük)",
        moq: "250 Kg",
        fiyat_carpanlari: "250kg:1.00 / 500kg:0.92 / 1ton:0.85",
        hammadde_turu: "PLA / Nişasta",
        kalinlik_seviyesi: "50 Mikron",
        baski_durumu: "Baskılı (Çevreci)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "El Geçme (Punch)",
        koruk_detayi: "Alt Körük",
        geridonusum_orani: "%100 Kompostlanabilir",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Mat Yeşil / Doğal",
        irsaliye_cebi_detay: "Doğada Çözünür Baskılı",
        uyumlu_sektorler: "Çevreci Markalar, Organik Gıda, Butikler",
        kullanim_amaci: "Doğa dostu, kompostlanabilir taşımacılık çözümü",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      }
    ]
  },
  {
    id: "tx-parent-14",
    name: "Kraft Çantalar",
    desc: "Doğal görünümlü kahverengi/beyaz burgu saplı kağıt çanta; paket servis, fırın ve mağazalar için ideal.",
    categoryKey: "kagit_karton",
    categoryLabel: "KAĞIT VE KARTON ÇANTALAR",
    malzeme: "Kraft Kağıt",
    specLabel: "Gramaj",
    specValue: "100 Gr/m²",
    baski: "Baskılı",
    unitText: "Birim Fiyat (3.000 Adet Başlayan)",
    priceText: "₺3.40'den",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı", "Eko-Dostu"],
    imgUrl: IMAGES.kraftCanta,
    variants: [
      {
        sira_no: 68,
        urun_kodu: "KRF-1825-68",
        olculer: "18 x 25 + 8 (Yan Körük)",
        moq: "3.000 Adet",
        fiyat_carpanlari: "3k:1.00 / 10k:0.90 / 30k:0.83",
        hammadde_turu: "Kraft Kağıt",
        kalinlik_seviyesi: "100 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Büküm Kağıt Sap",
        koruk_detayi: "Yan & Alt Körük",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "15 İş Günü",
        zemin_rengi: "Doğal Kahve Kraft",
        irsaliye_cebi_detay: "Takviyeli Taban",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.04",
        multipliers: {"3000": 1.0, "10000": 0.9, "30000": 0.83}
      },
      {
        sira_no: 69,
        urun_kodu: "KRF-2532-69",
        olculer: "25 x 32 + 8 (Yan Körük)",
        moq: "3.000 Adet",
        fiyat_carpanlari: "3k:1.00 / 10k:0.90 / 30k:0.83",
        hammadde_turu: "Kraft Kağıt",
        kalinlik_seviyesi: "100 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Büküm Kağıt Sap",
        koruk_detayi: "Yan & Alt Körük",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "15 İş Günü",
        zemin_rengi: "Doğal Kahve Kraft",
        irsaliye_cebi_detay: "Takviyeli Taban",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺2.99",
        multipliers: {"3000": 1.0, "10000": 0.9, "30000": 0.83}
      },
      {
        sira_no: 70,
        urun_kodu: "KRF-3242-70",
        olculer: "32 x 42 + 12 (Yan Körük)",
        moq: "3.000 Adet",
        fiyat_carpanlari: "3k:1.00 / 10k:0.90 / 30k:0.83",
        hammadde_turu: "Kraft Kağıt",
        kalinlik_seviyesi: "110 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Büküm Kağıt Sap",
        koruk_detayi: "Yan & Alt Körük",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "15 İş Günü",
        zemin_rengi: "Doğal Kahve Kraft",
        irsaliye_cebi_detay: "Takviyeli Taban",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺5.02",
        multipliers: {"3000": 1.0, "10000": 0.9, "30000": 0.83}
      }
    ]
  },
  {
    id: "tx-parent-15",
    name: "Lüks Karton Çantalar",
    desc: "Lüks segment butikler, kuyumcular ve kozmetik markaları için kalın kuşe karton ve ip saplı lüks çanta.",
    categoryKey: "kagit_karton",
    categoryLabel: "KAĞIT VE KARTON ÇANTALAR",
    malzeme: "Kuşe Karton",
    specLabel: "Gramaj",
    specValue: "230 Gr/m²",
    baski: "Baskılı (Laminasyon)",
    unitText: "Birim Fiyat (3.000 Adet Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı (Laminasyon)"],
    imgUrl: IMAGES.luksKarton,
    variants: [
      {
        sira_no: 71,
        urun_kodu: "KRT-1825-71",
        olculer: "18 x 25 + 8 (Yan Körük)",
        moq: "3.000 Adet",
        fiyat_carpanlari: "3k:1.00 / 10k:0.90 / 30k:0.83",
        hammadde_turu: "Kuşe Karton",
        kalinlik_seviyesi: "230 Gr/m²",
        baski_durumu: "Baskılı (Laminasyon)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "İpli Sap (Kordon)",
        koruk_detayi: "Yan & Alt Körük",
        geridonusum_orani: "Geri Dönüştürülebilir",
        termin_suresi: "15 İş Günü",
        zemin_rengi: "Özel Tasarım Renkli",
        irsaliye_cebi_detay: "Karton Destekli Pano",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Siparişle",
        baski_renk_yon: "4 + 0 (CMYK)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"3000": 1.0, "10000": 0.9, "30000": 0.83}
      },
      {
        sira_no: 72,
        urun_kodu: "KRT-2532-72",
        olculer: "25 x 32 + 8 (Yan Körük)",
        moq: "3.000 Adet",
        fiyat_carpanlari: "3k:1.00 / 10k:0.90 / 30k:0.83",
        hammadde_turu: "Kuşe Karton",
        kalinlik_seviyesi: "230 Gr/m²",
        baski_durumu: "Baskılı (Laminasyon)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "İpli Sap (Kordon)",
        koruk_detayi: "Yan & Alt Körük",
        geridonusum_orani: "Geri Dönüştürülebilir",
        termin_suresi: "15 İş Günü",
        zemin_rengi: "Özel Tasarım Renkli",
        irsaliye_cebi_detay: "Karton Destekli Pano",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Siparişle",
        baski_renk_yon: "4 + 0 (CMYK)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"3000": 1.0, "10000": 0.9, "30000": 0.83}
      },
      {
        sira_no: 73,
        urun_kodu: "KRT-3242-73",
        olculer: "32 x 42 + 12 (Yan Körük)",
        moq: "3.000 Adet",
        fiyat_carpanlari: "3k:1.00 / 10k:0.90 / 30k:0.83",
        hammadde_turu: "Kuşe Karton",
        kalinlik_seviyesi: "250 Gr/m²",
        baski_durumu: "Baskılı (Laminasyon)",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "İpli Sap (Kordon)",
        koruk_detayi: "Yan & Alt Körük",
        geridonusum_orani: "Geri Dönüştürülebilir",
        termin_suresi: "15 İş Günü",
        zemin_rengi: "Özel Tasarım Renkli",
        irsaliye_cebi_detay: "Karton Destekli Pano",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Siparişle",
        baski_renk_yon: "4 + 1 (İç-Dış)",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"3000": 1.0, "10000": 0.9, "30000": 0.83}
      }
    ]
  },
  {
    id: "tx-parent-16",
    name: "Kese Kağıtları",
    desc: "Fırıncılık, unlu mamuller ve fast-food zincirleri için dipli/dipsiz neme dayanıklı şık kese kağıtları.",
    categoryKey: "kagit_karton",
    categoryLabel: "KAĞIT VE KARTON ÇANTALAR",
    malzeme: "Sülfit Kağıt",
    specLabel: "Gramaj",
    specValue: "50 Gr/m²",
    baski: "Baskısız",
    unitText: "Birim Fiyat (150 Kg Başlayan)",
    priceText: "₺0.85'den",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız", "Eko-Dostu", "Çok Satan"],
    imgUrl: IMAGES.keseKagidi,
    variants: [
      {
        sira_no: 74,
        urun_kodu: "KSE-1020-74",
        olculer: "10 x 20 + 4 (Yan Körük)",
        moq: "150 Kg",
        fiyat_carpanlari: "150kg:1.00 / 500kg:0.88",
        hammadde_turu: "Sülfit Kağıt",
        kalinlik_seviyesi: "50 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yok",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "5 İş Günü",
        zemin_rengi: "Gıda Uyumlu Esmer",
        irsaliye_cebi_detay: "Pürüzsüz İç Yüzey",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.51",
        multipliers: {}
      },
      {
        sira_no: 75,
        urun_kodu: "KSE-1525-75",
        olculer: "15 x 25 + 5 (Yan Körük)",
        moq: "150 Kg",
        fiyat_carpanlari: "150kg:1.00 / 500kg:0.88",
        hammadde_turu: "Sülfit Kağıt",
        kalinlik_seviyesi: "50 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yok",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "5 İş Günü",
        zemin_rengi: "Gıda Uyumlu Esmer",
        irsaliye_cebi_detay: "Pürüzsüz İç Yüzey",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.51",
        multipliers: {}
      },
      {
        sira_no: 76,
        urun_kodu: "KSE-2030-76",
        olculer: "20 x 30 + 6 (Yan Körük)",
        moq: "150 Kg",
        fiyat_carpanlari: "150kg:1.00 / 500kg:0.88",
        hammadde_turu: "Sülfit Kağıt",
        kalinlik_seviyesi: "55 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yok",
        koruk_detayi: "Yan Körük",
        geridonusum_orani: "%100 Doğa Dostu",
        termin_suresi: "5 İş Günü",
        zemin_rengi: "Gıda Uyumlu Esmer",
        irsaliye_cebi_detay: "Pürüzsüz İç Yüzey",
        uyumlu_sektorler: "Lüks Butikler, Restoran Paket Servis, Cafeler",
        kullanim_amaci: "Premium ve ekolojik paketleme/taşıma çantası",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Kg",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "₺0.56",
        multipliers: {}
      }
    ]
  },
  {
    id: "tx-parent-17",
    name: "Nonwoven (Tela) Çantalar",
    desc: "Uzun ömürlü, çok kullanımlık (ultrasonik dikişli) ekonomik, dayanıklı ekolojik bez çanta.",
    categoryKey: "bez_tela",
    categoryLabel: "BEZ VE TELA ÇANTALAR",
    malzeme: "%100 PP Tela",
    specLabel: "Gramaj",
    specValue: "80 Gr/m²",
    baski: "Baskılı",
    unitText: "Birim Fiyat (1.000 Adet Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı"],
    imgUrl: IMAGES.telaCanta,
    variants: [
      {
        sira_no: 77,
        urun_kodu: "TLA-2535-77",
        olculer: "25 x 35",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 5k:0.90 / 10k:0.84",
        hammadde_turu: "%100 PP Tela",
        kalinlik_seviyesi: "80 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Tela Saplı",
        koruk_detayi: "Yok",
        geridonusum_orani: "Çok Kullanımlık",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Standart Tela Rengi",
        irsaliye_cebi_detay: "Ultrasonik Kaynaklı",
        uyumlu_sektorler: "Promosyon, Fuar Organizasyon, Kurumsal Hediyelik",
        kullanim_amaci: "Uzun ömürlü, reklam odaklı çok kullanımlık çanta",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"1000": 1.0, "5000": 0.9, "10000": 0.84}
      },
      {
        sira_no: 78,
        urun_kodu: "TLA-3040-78",
        olculer: "30 x 40",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 5k:0.90 / 10k:0.84",
        hammadde_turu: "%100 PP Tela",
        kalinlik_seviyesi: "80 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Tela Saplı",
        koruk_detayi: "Yok",
        geridonusum_orani: "Çok Kullanımlık",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Standart Tela Rengi",
        irsaliye_cebi_detay: "Ultrasonik Kaynaklı",
        uyumlu_sektorler: "Promosyon, Fuar Organizasyon, Kurumsal Hediyelik",
        kullanim_amaci: "Uzun ömürlü, reklam odaklı çok kullanımlık çanta",
        stok_durumu: "Siparişle",
        baski_renk_yon: "1 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"1000": 1.0, "5000": 0.9, "10000": 0.84}
      },
      {
        sira_no: 79,
        urun_kodu: "TLA-3540-79",
        olculer: "35 x 40",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 5k:0.90 / 10k:0.84",
        hammadde_turu: "%100 PP Tela",
        kalinlik_seviyesi: "80 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Tela Saplı",
        koruk_detayi: "Yok",
        geridonusum_orani: "Çok Kullanımlık",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Standart Tela Rengi",
        irsaliye_cebi_detay: "Ultrasonik Kaynaklı",
        uyumlu_sektorler: "Promosyon, Fuar Organizasyon, Kurumsal Hediyelik",
        kullanim_amaci: "Uzun ömürlü, reklam odaklı çok kullanımlık çanta",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"1000": 1.0, "5000": 0.9, "10000": 0.84}
      },
      {
        sira_no: 80,
        urun_kodu: "TLA-4050-80",
        olculer: "40 x 50",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 5k:0.90 / 10k:0.84",
        hammadde_turu: "%100 PP Tela",
        kalinlik_seviyesi: "90 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Tela Saplı",
        koruk_detayi: "Yok",
        geridonusum_orani: "Çok Kullanımlık",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Standart Tela Rengi",
        irsaliye_cebi_detay: "Ultrasonik Kaynaklı",
        uyumlu_sektorler: "Promosyon, Fuar Organizasyon, Kurumsal Hediyelik",
        kullanim_amaci: "Uzun ömürlü, reklam odaklı çok kullanımlık çanta",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 2",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"1000": 1.0, "5000": 0.9, "10000": 0.84}
      }
    ]
  },
  {
    id: "tx-parent-18",
    name: "Ham Bez (Pamuk) Çantalar",
    desc: "Doğal pamuklu ham bez kumaştan, uzun kollu, marka bilinirliğini sokaklara taşıyacak taşıma çantası.",
    categoryKey: "bez_tela",
    categoryLabel: "BEZ VE TELA ÇANTALAR",
    malzeme: "%100 Pamuk Bez",
    specLabel: "Gramaj",
    specValue: "140 Gr/m²",
    baski: "Baskılı",
    unitText: "Birim Fiyat (1.000 Adet Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Siparişle",
    badges: ["Baskılı", "Eko-Dostu"],
    imgUrl: IMAGES.hamBez,
    variants: [
      {
        sira_no: 81,
        urun_kodu: "BEZ-3040-81",
        olculer: "30 x 40",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 5k:0.90 / 10k:0.84",
        hammadde_turu: "%100 Pamuk Bez",
        kalinlik_seviyesi: "140 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Pamuk Omuz Sapı",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Doğal & Yıkanabilir",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Doğal Ham Renk (Krem)",
        irsaliye_cebi_detay: "Dikişli / Yıkanabilir",
        uyumlu_sektorler: "Promosyon, Fuar Organizasyon, Kurumsal Hediyelik",
        kullanim_amaci: "Uzun ömürlü, reklam odaklı çok kullanımlık çanta",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"1000": 1.0, "5000": 0.9, "10000": 0.84}
      },
      {
        sira_no: 82,
        urun_kodu: "BEZ-3540-82",
        olculer: "35 x 40",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 5k:0.90 / 10k:0.84",
        hammadde_turu: "%100 Pamuk Bez",
        kalinlik_seviyesi: "140 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Pamuk Omuz Sapı",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Doğal & Yıkanabilir",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Doğal Ham Renk (Krem)",
        irsaliye_cebi_detay: "Dikişli / Yıkanabilir",
        uyumlu_sektorler: "Promosyon, Fuar Organizasyon, Kurumsal Hediyelik",
        kullanim_amaci: "Uzun ömürlü, reklam odaklı çok kullanımlık çanta",
        stok_durumu: "Siparişle",
        baski_renk_yon: "2 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"1000": 1.0, "5000": 0.9, "10000": 0.84}
      },
      {
        sira_no: 83,
        urun_kodu: "BEZ-4050-83",
        olculer: "40 x 50",
        moq: "1.000 Adet",
        fiyat_carpanlari: "1k:1.00 / 5k:0.90 / 10k:0.84",
        hammadde_turu: "%100 Pamuk Bez",
        kalinlik_seviyesi: "140 Gr/m²",
        baski_durumu: "Baskılı",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Pamuk Omuz Sapı",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Doğal & Yıkanabilir",
        termin_suresi: "14 İş Günü",
        zemin_rengi: "Doğal Ham Renk (Krem)",
        irsaliye_cebi_detay: "Dikişli / Yıkanabilir",
        uyumlu_sektorler: "Promosyon, Fuar Organizasyon, Kurumsal Hediyelik",
        kullanim_amaci: "Uzun ömürlü, reklam odaklı çok kullanımlık çanta",
        stok_durumu: "Siparişle",
        baski_renk_yon: "3 + 0",
        satis_sekli: "Adet",
        birim_fiyati: 0,
        para_birimi: "USD",
        priceText: "Fiyat Alınız",
        multipliers: {"1000": 1.0, "5000": 0.9, "10000": 0.84}
      }
    ]
  },
  {
    id: "tx-parent-19",
    name: "Balonlu Patpat Naylonlar",
    desc: "Mobilya, cam ve kıymetli eşya taşımacılığında kırılmaları önleyen rulo balonlu koruyucu ambalaj.",
    categoryKey: "koruyucu_endustriyel",
    categoryLabel: "KORUYUCU VE ENDÜSTRİYEL AMBALAJ",
    malzeme: "LDPE",
    specLabel: "Gramaj",
    specValue: "50 Gr/m²",
    baski: "Baskısız",
    unitText: "Birim Fiyat (20 Rulo Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız", "Çok Satan"],
    imgUrl: IMAGES.balonluPatpat,
    variants: [
      {
        sira_no: 84,
        urun_kodu: "IND-100cmx50mtRulo-84",
        olculer: "100 cm x 50 mt Rulo",
        moq: "20 Rulo",
        fiyat_carpanlari: "Hacme Göre İskonto Uygulanır",
        hammadde_turu: "LDPE",
        kalinlik_seviyesi: "50 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "4 İş Günü",
        zemin_rengi: "Şeffaf Patpat",
        irsaliye_cebi_detay: "Hava Kabarcıklı Koruma",
        uyumlu_sektorler: "Fabrikalar, Üretim Tesisleri, Depolar, Lojistik Merkezleri",
        kullanim_amaci: "Palet Koruma, shrinkleme ve ağır sanayi ambalajlama",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet (Rulo)",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 85,
        urun_kodu: "IND-120cmx50mtRulo-85",
        olculer: "120 cm x 50 mt Rulo",
        moq: "20 Rulo",
        fiyat_carpanlari: "Hacme Göre İskonto Uygulanır",
        hammadde_turu: "LDPE",
        kalinlik_seviyesi: "50 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "4 İş Günü",
        zemin_rengi: "Şeffaf Patpat",
        irsaliye_cebi_detay: "Hava Kabarcıklı Koruma",
        uyumlu_sektorler: "Fabrikalar, Üretim Tesisleri, Depolar, Lojistik Merkezleri",
        kullanim_amaci: "Palet Koruma, shrinkleme ve ağır sanayi ambalajlama",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet (Rulo)",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      },
      {
        sira_no: 86,
        urun_kodu: "IND-150cmx50mtRulo-86",
        olculer: "150 cm x 50 mt Rulo",
        moq: "20 Rulo",
        fiyat_carpanlari: "Hacme Göre İskonto Uygulanır",
        hammadde_turu: "LDPE",
        kalinlik_seviyesi: "55 Gr/m²",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "4 İş Günü",
        zemin_rengi: "Şeffaf Patpat",
        irsaliye_cebi_detay: "Hava Kabarcıklı Koruma",
        uyumlu_sektorler: "Fabrikalar, Üretim Tesisleri, Depolar, Lojistik Merkezleri",
        kullanim_amaci: "Palet Koruma, shrinkleme ve ağır sanayi ambalajlama",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Adet (Rulo)",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      }
    ]
  },
  {
    id: "tx-parent-20",
    name: "Şrink Filmler (P.E, POF, PVC)",
    desc: "Ürünlerinizi ısı yardımıyla sıkıca sararak toz, kir ve nemden koruyan endüstriyel şrink rulo film.",
    categoryKey: "koruyucu_endustriyel",
    categoryLabel: "KORUYUCU VE ENDÜSTRİYEL AMBALAJ",
    malzeme: "POF (Polyolefin)",
    specLabel: "Kalınlık",
    specValue: "19 Mikron",
    baski: "Baskısız",
    unitText: "Birim Fiyat (500 Kg Başlayan)",
    priceText: "Fiyat Alınız",
    isPremiumPrice: true,
    stokDurumu: "Var",
    badges: ["Baskısız"],
    imgUrl: IMAGES.srinkFilm,
    variants: [
      {
        sira_no: 87,
        urun_kodu: "IND-Bobin/Rulo-87",
        olculer: "Bobin / Rulo (Özel En)",
        moq: "500 Kg",
        fiyat_carpanlari: "Hacme Göre İskonto Uygulanır",
        hammadde_turu: "POF (Polyolefin)",
        kalinlik_seviyesi: "19 Mikron",
        baski_durumu: "Baskısız",
        kargo_bant_tipi: "Yok",
        kulp_tipi: "Yok",
        koruk_detayi: "Yok",
        geridonusum_orani: "%100 Geri Dönüşebilir",
        termin_suresi: "4 İş Günü",
        zemin_rengi: "Şeffaf Rulo",
        irsaliye_cebi_detay: "Isıyla Büzüşen Yapı",
        uyumlu_sektorler: "Fabrikalar, Üretim Tesisleri, Depolar, Lojistik Merkezleri",
        kullanim_amaci: "Palet Koruma, shrinkleme ve ağır sanayi ambalajlama",
        stok_durumu: "Var",
        baski_renk_yon: "0 + 0 (Düz)",
        satis_sekli: "Kg (Bobin)",
        birim_fiyati: 0,
        para_birimi: "TL",
        priceText: "Fiyat Alınız",
        multipliers: {}
      }
    ]
  }
];

export const getProductByName = (name: string): TaxonomyProduct | undefined => {
  const clean = name.toLowerCase();
  return TAXONOMY_PRODUCTS.find(p => p.name.toLowerCase().includes(clean) || clean.includes(p.name.toLowerCase()));
};